# = OrderInfo Knowledge Base Updater Config =
# The kb updater tracks information from the refbox, compares it to
# the information in the knowledge base, and issues update as necessary.

# == Type of Order Instances ==
order_instance_type: order

order_complexity_predicate: ordercomplexity
order_base_color_predicate: orderbasecolor
order_ring1_color_predicate: orderring1color
order_ring2_color_predicate: orderring2color
order_ring3_color_predicate: orderring3color
order_cap_color_predicate: ordercapcolor
order_delivery_gate_predicate: ordergate
order_delivery_period_begin_predicate: orderdeliverybegin
order_delivery_period_end_predicate: orderdeliveryend

order_id_argument: ord
order_complexity_argument: com
order_color_argument: col
order_gate_argument: gat

order_object_prefix: o
gate_object_prefix: GATE-
order_complexity_object_prefix: c

# Value mapping for colors

rs_ring_value_blue: RING_BLUE
rs_ring_value_green: RING_GREEN
rs_ring_value_orange: RING_ORANGE
rs_ring_value_yellow: RING_YELLOW

base_color_value_red: BASE_RED
base_color_value_black: BASE_BLACK
base_color_value_silver: BASE_SILVER

cap_color_value_black: CAP_BLACK
cap_color_value_grey: CAP_GREY

